/**
 * Created by cesar on 26/10/16.
 *
 * \[(\d)\].
 * .$1.
 */
export const exportFields = {
    "Email": "emails[0].address",
    "Father first Name": "parents[0].firstName",
    "Father surname": "parents[0].surname",
    "Father gender": "parents[0].gender",
    "Father mobilePhone": "parents[0].mobilePhone",
    "Father blue Card Number": "parents[0].blueCard.number",
    "Father blue Card Expiry Date": "parents[0].blueCard.expiry",
    "Father blue Card Status": "parents[0].blueCard.status",
    "Father email": "parents[0].email",
    "Mother first Name": "parents[1].firstName",
    "Mother surname": "parents[1].surname",
    "Mother gender": "parents[1].gender",
    "Mother mobile Phone": "parents[1].mobilePhone",
    "Mother blue Card Number": "parents[1].blueCard.number",
    "Mother blue Card Expiry Date": "parents[1].blueCard.expiry",
    "Mother blue Card Status": "parents[1].blueCard.status",
    "Mother email": "parents[1].email",
    "Home Phone": "contact.homePhone",
    "full Address": "contact.address.fullAddress",
    "street": "contact.address.street",
    "suburb": "contact.address.suburb",
    "city": "contact.address.city",
    "zip": "contact.address.zip",
    "Children 1 first Name": "children[0].firstName",
    "Children 1 gender": "children[0].gender",
    "Children 1 dateOfBirth": "children[0].dateOfBirth",
    "Children 1 nameOfSchool": "children[0].nameOfSchool",
    "Children 1 blueCard.number": "children[0].blueCard.number",
    "Children 1 blueCard.expiry": "children[0].blueCard.expiry",
    "Children 2 firstName": "children[1].firstName",
    "Children 2 gender": "children[1].gender",
    "Children 2 dateOfBirth": "children[1].dateOfBirth",
    "Children 2 nameOfSchool": "children[1].nameOfSchool",
    "Children 2 blueCard.number": "children[1].blueCard.number",
    "Children 2 blueCard.expiry": "children[1].blueCard.expiry",
    "Children 3 firstName": "children[2].firstName",
    "Children 3 gender": "children[2].gender",
    "Children 3 dateOfBirth": "children[2].dateOfBirth",
    "Children 3 nameOfSchool": "children[2].nameOfSchool",
    "Children 3 blueCard.number": "children[2].blueCard.number",
    "Children 3 blueCard.expiry": "children[2].blueCard.expiry",
    "Children 4 firstName": "children[3].firstName",
    "Children 4 gender": "children[3].gender",
    "Children 4 dateOfBirth": "children[3].dateOfBirth",
    "Children 4 nameOfSchool": "children[3].nameOfSchool",
    "Children 4 blueCard.number": "children[3].blueCard.number",
    "Children 4 blueCard.expiry": "children[3].blueCard.expiry",
    "Children 5 firstName": "children[4].firstName",
    "Children 5 gender": "children[4].gender",
    "Children 5 dateOfBirth": "children[4].dateOfBirth",
    "Children 5 nameOfSchool": "children[4].nameOfSchool",
    "Children 5 blueCard.number": "children[4].blueCard.number",
    "Children 5 blueCard.expiry": "children[4].blueCard.expiry",
    "Children 6 firstName": "children[5].firstName",
    "Children 6 gender": "children[5].gender",
    "Children 6 dateOfBirth": "children[5].dateOfBirth",
    "Children 6 nameOfSchool": "children[5].nameOfSchool",
    "Children 6 blueCard.number": "children[5].blueCard.number",
    "Children 6 blueCard.expiry": "children[5].blueCard.expiry",
    "Guest 1 firstName": "guests[0].firstName",
    "Guest 1 surname": "guests[0].surname",
    "Guest 1 gender": "guests[0].gender",
    "Guest 1 dateOfBirth": "guests[0].dateOfBirth",
    "Guest 1 blueCard.number": "guests[0].blueCard.number",
    "Guest 1 blueCard.expiry": "guests[0].blueCard.expiry",
    "Guest 2 firstName": "guests[1].firstName",
    "Guest 2 surname": "guests[1].surname",
    "Guest 2 gender": "guests[1].gender",
    "Guest 2 dateOfBirth": "guests[1].dateOfBirth",
    "Guest 2 blueCard.number": "guests[1].blueCard.number",
    "Guest 2 blueCard.expiry": "guests[1].blueCard.expiry",
    "Guest 3 firstName": "guests[3].firstName",
    "Guest 3 surname": "guests[3].surname",
    "Guest 3 gender": "guests[3].gender",
    "Guest 3 dateOfBirth": "guests[3].dateOfBirth",
    "Guest 3 blueCard.number": "guests[3].blueCard.number",
    "Guest 3 blueCard.expiry": "guests[3].blueCard.expiry",
    "Pet 1 type": "pets[0].type",
    "Pet 1 status": "pets[0].status",
    "Pet 2 type": "pets[1].type",
    "Pet 2 status": "pets[1].status",
    "Pet 3 type": "pets[2].type",
    "Pet 3 status": "pets[2].status",
    "Pet 4 type": "pets[3].type",
    "Pet 4 status": "pets[3].status",
    "Pet 5 type": "pets[4].type",
    "Pet 5 status": "pets[4].status",
    "Pet 6 type": "pets[5].type",
    "Pet 6 status": "pets[5].status",
    "Pet 7 type": "pets[6].type",
    "Pet 7 status": "pets[6].status",
    "Pet 8 type": "pets[7].type",
    "Pet 8 status": "pets[7].status",
    "Room 1 number Of Beds": "bedrooms[0].numberOfBeds",
    "Room 2 number Of Beds": "bedrooms[1].numberOfBeds",
    "Room 3 number Of Beds": "bedrooms[2].numberOfBeds",
    "Room 4 number Of Beds": "bedrooms[3].numberOfBeds",
    "Room 5 number Of Beds": "bedrooms[4].numberOfBeds",
    "Room 6 number Of Beds": "bedrooms[5].numberOfBeds",
    "Room 7 number Of Beds": "bedrooms[6].numberOfBeds",
    "Room 8 number Of Beds": "bedrooms[7].numberOfBeds",
    "bank Name": "bank.bankName",
    "account Name": "bank.accountName",
    "account BSB": "bank.accountBSB",
    "account Number": "bank.accountNumber",
    "preferred Gender": "other.preferredGender",
    "wiFi Internet": "other.wiFiInternet",
    "school Transport": "other.schoolTransport",
    "indoor Smoking": "other.indoorSmoking",
    "dietary Notes": "other.dietaryNotes",
    "family Interests": "other.familyInterests",
    "family Status": "office.familyStatus",
    "family SubStatus": "office.familySubStatus",
    "family Score": "office.familyScore",
    "home Score": "office.homeScore",
    "Blue card status": "blueCardStatus",
    "Avg Score": "office.score",
    "Beds Count": "numberOfBeds",
    "parents Count": "parentsCount",
    "children Count": "childrenCount",
    "bedrooms Count": "bedroomsCount",
    "pets Count": "petsCount",
    "guests Count": "guestsCount"
};
